### ISSUE TITLE
train-server get stuck and stops responding

### ISSUE THREAD

**Issue by mynameisguy** [allegroai/trains-server#27]
When running trains-server for few days the web server get stuck.
can't access the web gui.
the training jobs seems to get stuck as well (which is the most significant issue for me). I get the errors:
```
Retrying (Retry(total=82, connect=240, read=82, redirect=240, status=240)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='...', port=8008): Read timed out. (read ti
meout=300.0)")': /v1.5/events.add_batch                                                                                                                                                                            
Retrying (Retry(total=101, connect=240, read=101, redirect=240, status=240)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='...', port=8008): Read timed out. (read 
timeout=300.0)")': /v1.5/models.create                                                                                                                                                                             
Retrying (Retry(total=81, connect=240, read=81, redirect=240, status=240)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='...', port=8008): Read timed out. (read ti
meout=300.0)")': /v1.5/events.add_batch                                                                                                                                                                            
Retrying (Retry(total=81, connect=240, read=81, redirect=240, status=240)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='...', port=8008): Read timed out. (read ti
meout=300.0)")': /v1.9/tasks.get_by_id                                                                                                                                                                             
```

when trying to shut down trains-server using docker compose down I get:
```
Stopping trains-webserver  ... done
Stopping trains-apiserver  ...
Stopping trains-mongo      ... error
Stopping trains-elastic    ... error
Stopping trains-fileserver ... error

ERROR: for trains-apiserver  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```
ctrl+c in the trains-server session and then docker compose down works.

after the restart trains-server works and all experiments continue.

**Comment by bmartinn** [comment]
Hi,
Can you please share the server's logs (located in `/opt/trains/logs`)?

**Comment by mynameisguy** [comment]
sure.

this seems like the relevant parts:
```
[2019-10-15 04:40:19,882] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 51ms
[2019-10-15 04:40:21,017] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 36ms
[2019-10-15 04:40:21,088] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 30ms
[2019-10-15 04:40:21,104] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 52ms
[2019-10-15 04:40:21,578] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 34ms
[2019-10-15 04:40:21,819] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 79ms
[2019-10-15 04:40:21,832] [9] [ERROR] [trains.server] Failed processing request http://...:8008/v1.9/tasks.get_by_id: 'json'
Traceback (most recent call last):
  File "server.py", line 52, in before_request
    content, content_type = ServiceRepo.handle_call(call)
  File "/opt/trains/server/service_repo/service_repo.py", line 284, in handle_call
    call.mark_end()
  File "/opt/trains/server/service_repo/apicall.py", line 511, in mark_end
    self.stats = timing_context.stats()
  File "/opt/trains/server/timing_context.py", line 11, in stats
    aggregate()
  File "/opt/trains/server/timing_context.py", line 32, in aggregate
    for op in _stats[comp]:
KeyError: 'json'
[2019-10-15 04:40:21,880] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 51ms
[2019-10-15 04:40:21,942] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 48ms
[2019-10-15 04:40:22,439] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 48ms
[2019-10-15 04:40:23,020] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 37ms
[2019-10-15 04:40:23,112] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 54ms

```
and this:


```
[2019-10-15 04:51:49,450] [9] [INFO] [trains.service_repo] Returned 200 for tasks.completed in 16ms
[2019-10-15 04:51:49,473] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 45ms
[2019-10-15 04:59:18,309] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 02:59:18.309012
[2019-10-15 04:59:18,313] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 05:14:18,413] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 03:14:18.413051
[2019-10-15 05:14:18,422] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 05:29:18,513] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 03:29:18.512815
[2019-10-15 05:29:18,517] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 05:44:18,594] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 03:44:18.594105
[2019-10-15 05:44:18,602] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 05:59:18,701] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 03:59:18.700931
[2019-10-15 05:59:18,705] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 06:14:18,806] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 04:14:18.805998
[2019-10-15 06:14:18,814] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 06:29:18,872] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 04:29:18.871929
[2019-10-15 06:29:18,876] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 06:44:18,977] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 04:44:18.976875
[2019-10-15 06:44:18,984] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 06:54:33,055] [9] [INFO] [trains.service_repo] Returned 200 for projects.get_all_ex in 41ms
[2019-10-15 06:54:33,075] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_all_ex in 51ms
[2019-10-15 06:54:35,115] [9] [INFO] [trains.service_repo] Returned 200 for projects.get_all_ex in 8ms
[2019-10-15 06:54:35,269] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_all_ex in 156ms
[2019-10-15 06:55:32,438] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_all_ex in 41ms
[2019-10-15 06:55:37,187] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_all_ex in 108ms
[2019-10-15 06:55:37,238] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_all_ex in 149ms
[2019-10-15 06:55:39,149] [9] [INFO] [trains.service_repo] Returned 200 for events.scalar_metrics_iter_histogram in 1849ms
[2019-10-15 06:59:19,086] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 04:59:19.086070
[2019-10-15 06:59:19,089] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 07:14:19,125] [9] [INFO] [trains.non_responsive_tasks_watchdog] Starting cleanup cycle for running tasks last updated before 2019-10-15 05:14:19.125028
[2019-10-15 07:14:19,129] [9] [INFO] [trains.non_responsive_tasks_watchdog] Done
[2019-10-15 07:15:25,326] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_all_ex in 103ms
[2019-10-15 07:16:34,513] [9] [INFO] [trains.service_repo] Returned 200 for auth.login in 24ms
[2019-10-15 07:16:34,551] [9] [INFO] [trains.service_repo] Returned 200 for projects.get_all in 10ms
[2019-10-15 07:16:34,662] [9] [INFO] [trains.service_repo] Returned 200 for tasks.create in 25ms
[2019-10-15 07:16:34,683] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 9ms
[2019-10-15 07:16:34,744] [9] [INFO] [trains.service_repo] Returned 200 for tasks.started in 16ms
[2019-10-15 07:16:34,775] [9] [INFO] [trains.service_repo] Returned 200 for tasks.started in 13ms
[2019-10-15 07:16:34,798] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 9ms
[2019-10-15 07:16:34,841] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 10ms
[2019-10-15 07:16:34,916] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 24ms
[2019-10-15 07:16:34,958] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 13ms
[2019-10-15 07:16:35,658] [9] [INFO] [trains.service_repo] Returned 200 for tasks.set_requirements in 11ms
[2019-10-15 07:16:35,684] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 11ms
[2019-10-15 07:16:36,586] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 23ms
[2019-10-15 07:16:36,634] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 28ms
[2019-10-15 07:16:36,904] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 14ms
[2019-10-15 07:16:36,930] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 49ms
[2019-10-15 07:16:38,924] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 39ms
[2019-10-15 07:16:38,942] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 11ms
[2019-10-15 07:16:40,969] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 11ms
[2019-10-15 07:16:43,000] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 11ms
[2019-10-15 07:16:43,947] [9] [INFO] [trains.service_repo] Returned 200 for tasks.stopped in 26ms
[2019-10-15 07:16:43,967] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 36ms
[2019-10-15 07:17:04,489] [9] [INFO] [trains.service_repo] Returned 200 for auth.login in 19ms
[2019-10-15 07:17:04,615] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_all in 8ms
[2019-10-15 07:17:04,641] [9] [INFO] [trains.service_repo] Returned 200 for projects.get_by_id in 7ms
[2019-10-15 07:17:04,669] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 11ms
[2019-10-15 07:17:04,720] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 9ms
[2019-10-15 07:17:04,900] [9] [INFO] [trains.service_repo] Returned 200 for tasks.reset in 165ms
[2019-10-15 07:17:04,929] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 12ms
[2019-10-15 07:17:04,967] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 14ms
[2019-10-15 07:17:05,006] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 19ms
[2019-10-15 07:17:05,042] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 16ms
[2019-10-15 07:17:05,066] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 10ms
[2019-10-15 07:17:05,108] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 17ms
[2019-10-15 07:17:05,147] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 19ms
[2019-10-15 07:17:05,183] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 17ms
[2019-10-15 07:17:05,219] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 17ms
[2019-10-15 07:17:05,251] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 14ms
[2019-10-15 07:17:05,280] [9] [INFO] [trains.service_repo] Returned 200 for tasks.started in 13ms
[2019-10-15 07:17:05,303] [9] [INFO] [trains.service_repo] Returned 200 for projects.get_by_id in 6ms
[2019-10-15 07:17:05,338] [9] [INFO] [trains.service_repo] Returned 200 for tasks.started in 16ms
[2019-10-15 07:17:05,363] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 10ms
[2019-10-15 07:17:05,394] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 11ms
[2019-10-15 07:17:05,515] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 22ms
[2019-10-15 07:17:05,544] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 10ms
[2019-10-15 07:17:06,598] [9] [INFO] [trains.service_repo] Returned 200 for tasks.set_requirements in 13ms
[2019-10-15 07:17:06,620] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 10ms
[2019-10-15 07:17:06,841] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 20ms
[2019-10-15 07:17:06,889] [9] [INFO] [trains.service_repo] Returned 200 for tasks.edit in 25ms
[2019-10-15 07:17:07,372] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 38ms
[2019-10-15 07:17:07,470] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 13ms
[2019-10-15 07:17:09,369] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 36ms
[2019-10-15 07:17:09,502] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 11ms
[2019-10-15 07:17:11,533] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 12ms
[2019-10-15 07:17:13,567] [9] [INFO] [trains.service_repo] Returned 200 for tasks.get_by_id in 10ms
[2019-10-15 07:17:14,931] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 74ms
[2019-10-15 07:17:15,105] [9] [INFO] [trains.service_repo] Returned 200 for tasks.failed in 22ms
[2019-10-15 07:17:15,131] [9] [INFO] [trains.service_repo] Returned 200 for events.add_batch in 39ms
```

let me know if you need any more information

**Comment by bmartinn** [comment]
Okay, I think I have a workaround until we release the next version with a fix.

Try running the attached docker compose, instead of the original one.
Let me know if it solved the issue for the time being.

(Due to GitHub limits, you have to rename the attached file from .txt to .yml )
[docker-compose-gunicorn.yml.txt](https://github.com/allegroai/trains-server/files/3733765/docker-compose-gunicorn.yml.txt)

**Comment by mynameisguy** [comment]
thanks
currently running. will update in few days

**Comment by mynameisguy** [comment]
didn't crash, so it definitely more stable than before.
thanks!
