### ISSUE TITLE
Fail to migrate to new version

### ISSUE THREAD

**Issue by lamhoangtung** [allegroai/trains-server#55]
Hi I'm trying to update to a new version of `trains-server` with:

```bash
docker-compose -f docker-compose.yml pull
docker-compose -f docker-compose.yml up
```
and getting this error:

```bash
trains-apiserver  | [2020-07-27 09:01:48,090] [8] [ERROR] [trains.mongo.initialize.migration] Failed applying /opt/trains/server/mongo/migrations/0.14.0.py:migrate_auth()
trains-apiserver  | Traceback (most recent call last):
trains-apiserver  |   File "/opt/trains/server/mongo/initialize/migration.py", line 70, in _apply_migrations
trains-apiserver  |     func(get_db(alias))
trains-apiserver  |   File "/opt/trains/server/mongo/migrations/0.14.0.py", line 35, in migrate_auth
trains-apiserver  |     collection.drop_index("name_1_company_1")
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 2116, in drop_index
trains-apiserver  |     session=session)
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 250, in _command
trains-apiserver  |     user_fields=user_fields)
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/pool.py", line 613, in command
trains-apiserver  |     user_fields=user_fields)
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/network.py", line 167, in command
trains-apiserver  |     parse_write_concern_error=parse_write_concern_error)
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
trains-apiserver  |     raise OperationFailure(msg % errmsg, code, response)
trains-apiserver  | pymongo.errors.OperationFailure: index not found with name [name_1_company_1]
trains-apiserver  | [2020-07-27 09:01:48,092] [8] [ERROR] [trains.mongo.initialize] Failed initializing mongodb
trains-apiserver  | Traceback (most recent call last):
trains-apiserver  |   File "/opt/trains/server/mongo/initialize/migration.py", line 70, in _apply_migrations
trains-apiserver  |     func(get_db(alias))
trains-apiserver  |   File "/opt/trains/server/mongo/migrations/0.14.0.py", line 35, in migrate_auth
trains-apiserver  |     collection.drop_index("name_1_company_1")
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 2116, in drop_index
trains-apiserver  |     session=session)
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 250, in _command
trains-apiserver  |     user_fields=user_fields)
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/pool.py", line 613, in command
trains-apiserver  |     user_fields=user_fields)
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/network.py", line 167, in command
trains-apiserver  |     parse_write_concern_error=parse_write_concern_error)
trains-apiserver  |   File "/usr/local/lib64/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
trains-apiserver  |     raise OperationFailure(msg % errmsg, code, response)
trains-apiserver  | pymongo.errors.OperationFailure: index not found with name [name_1_company_1]
trains-apiserver  |
trains-apiserver  | During handling of the above exception, another exception occurred:
trains-apiserver  |
trains-apiserver  | Traceback (most recent call last):
trains-apiserver  |   File "/opt/trains/server/mongo/initialize/__init__.py", line 16, in init_mongo_data
trains-apiserver  |     empty_dbs = _apply_migrations(log)
trains-apiserver  |   File "/opt/trains/server/mongo/initialize/migration.py", line 74, in _apply_migrations
trains-apiserver  |     "Migration failed, aborting. Please restore backup."
trains-apiserver  | ValueError: Migration failed, aborting. Please restore backup.
```

I have modify the `docker-compose.yml` file a bit to point to an old backup of ours `trains-server`, which is attached bellow (I have to change it to .txt because Github don't accept .yml file):

[old_docker-compose.yml.txt](https://github.com/allegroai/trains-server/files/4981053/old_docker-compose.yml.txt)

And here is the original docker compose file before the upgrade:

[new_docker-compose.yml.txt](https://github.com/allegroai/trains-server/files/4981052/new_docker-compose.yml.txt)

Can you guys help me out a bit here. Thanks <3

**Comment by jkhenning** [comment]
Hi @lamhoangtung,

Strange... This seems to be a failure in the auto-migration performed by the Trains Server on startup, which is caused by a missing index (that should have been there, assuming you're running a previous version). I can only surmise this is caused by migration from an older version (not one version behind), which was not properly tested...

What is the version you're trying to deploy, and what was your previous version?

We can easily circumvent this error manually if you're willing to follow a few instructions to execute inside the mongodb docker container 😄

**Comment by lamhoangtung** [comment]
@jkhenning I'm trying to update to the latest version available on docker hub and github master branch. I'm not sure what is the previous version of the backup that I'm trying to point to.

And sure give me your mongodb instruction, I will follow it. Thanks for the quick help ^^

**Comment by jkhenning** [comment]
@lamhoangtung while the server is down (`docker-compose down`) use the following command to open bash inside the mongodb docker container:
`docker exec -it trains-mongo /bin/bash`

Once inside the container, open the `mongo` client using the following command:
`mongo`

In the mongo client prompt, issue the following commands:
```
> use auth
> db.user.createIndex({name: 1, company: 1})
> exit
```

Use `Ctrl+D` or `exit` to exit from the container bash prompt.

Once that's done, the server migration should pass successfully - try again and let me know :)

**Comment by lamhoangtung** [comment]
@jkhenning. The migration seems to work:
```bash
trains-apiserver  | [2020-07-28 13:34:30,357] [8] [INFO] [trains.mongo.initialize.migration] Finished mongodb migrations
```
But I'm unable to login to the trains-server.

![Screen Shot 2020-07-28 at 8 37 37 PM](https://user-images.githubusercontent.com/26834698/88672973-46765c80-d112-11ea-8680-e081922af374.png)

Can you take a look ?

**Comment by jkhenning** [comment]
@lamhoangtung do you see any error in the apiserver log? can you send it?

Also, I'd like to see the developer's Network tab in more detail - i.e. see the response code for each call and the error message received from the server...

**Comment by lamhoangtung** [comment]
@jkhenning Here is the details of the Network tab

![Screen Shot 2020-07-28 at 9 26 57 PM](https://user-images.githubusercontent.com/26834698/88679542-bb00c980-d119-11ea-9ab2-59a8d9bbb891.png)
![Screen Shot 2020-07-28 at 9 27 14 PM](https://user-images.githubusercontent.com/26834698/88679551-bd632380-d119-11ea-8b05-f8dcd9c7dcd6.png)
![Screen Shot 2020-07-28 at 9 27 21 PM](https://user-images.githubusercontent.com/26834698/88679553-be945080-d119-11ea-8cd9-92f0919672b5.png)
![Screen Shot 2020-07-28 at 9 27 29 PM](https://user-images.githubusercontent.com/26834698/88679557-bf2ce700-d119-11ea-9f6f-8327ddfbe7fd.png)
![Screen Shot 2020-07-28 at 9 27 36 PM](https://user-images.githubusercontent.com/26834698/88679561-bfc57d80-d119-11ea-82df-baedfb8c0077.png)
![Screen Shot 2020-07-28 at 9 27 43 PM](https://user-images.githubusercontent.com/26834698/88679566-c05e1400-d119-11ea-9f27-94e6ea0409cf.png)
![Screen Shot 2020-07-28 at 9 27 53 PM](https://user-images.githubusercontent.com/26834698/88679570-c0f6aa80-d119-11ea-891b-4498f7b89ace.png)
![Screen Shot 2020-07-28 at 9 27 59 PM](https://user-images.githubusercontent.com/26834698/88679573-c18f4100-d119-11ea-89dc-0eb77343e961.png)
![Screen Shot 2020-07-28 at 9 28 05 PM](https://user-images.githubusercontent.com/26834698/88679575-c227d780-d119-11ea-9d73-ef9ad033ca9c.png)

Also I found this error:

```bash
trains-elastic    | [2020-07-28T14:24:53,071][WARN ][o.e.g.GatewayAllocator$InternalPrimaryShardAllocator] [trains] [events-training_debug_image-d1bd92a3b039400cbafc60a7a5b1e52b][2]: failed to list shard for shard_started on node [Lv1ysgPFRCmfE2HgDrYymA]        [179/1999]
trains-elastic    | org.elasticsearch.action.FailedNodeException: Failed node [Lv1ysgPFRCmfE2HgDrYymA]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure(TransportNodesAction.java:239) [elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$200(TransportNodesAction.java:153) [elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException(TransportNodesAction.java:211) [elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1085) [elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1189) [elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1167) [elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:673) [elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:660) [elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
trains-elastic    |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
trains-elastic    |     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
trains-elastic    | Caused by: org.elasticsearch.transport.RemoteTransportException: [trains][172.20.0.5:9300][internal:gateway/local/started_shards[n]]
trains-elastic    | Caused by: org.elasticsearch.ElasticsearchException: failed to load started shards
trains-elastic    |     at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:171) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     ... 3 more
trains-elastic    | Caused by: org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:66, legacy:false, file:/usr/share/elasticsearch/data/nodes/0/indices/bhYFCj9ZTjSY0MY94Heppw/_state/state-66.st]
trains-elastic    |     at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:196) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:335) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:127) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     ... 3 more
trains-elastic    | Caused by: java.io.IOException: failed to read [id:66, legacy:false, file:/usr/share/elasticsearch/data/nodes/0/indices/bhYFCj9ZTjSY0MY94Heppw/_state/state-66.st]
trains-elastic    |     at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:328) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:127) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     ... 3 more
trains-elastic    | Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/nodes/0/indices/bhYFCj9ZTjSY0MY94Heppw/_state/state-66.st
trains-elastic    |     at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:?]
trains-elastic    |     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
trains-elastic    |     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
trains-elastic    |     at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
trains-elastic    |     at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_201]
trains-elastic    |     at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_201]
trains-elastic    |     at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:77) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
trains-elastic    |     at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:188) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:323) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:127) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.16.jar:5.6.16]
trains-elastic    |     ... 3 more
```

**Comment by jkhenning** [comment]
Can you please send the Network info (including complete response) for the **auth.create_user** call? It will only show after you try to login (using any name)

**Comment by lamhoangtung** [comment]
@jkhenning 
Here you go
```json
{"meta":{"id":"191b689672344bb6ad0960890e8c3e68","trx":"191b689672344bb6ad0960890e8c3e68","endpoint":{"name":"auth.create_user","requested_version":"2.8","actual_version":"1.0"},"result_code":401,"result_subcode":22,"result_msg":"Unauthorized (invalid credentials) (failed to locate provided credentials)","error_stack":null},"data":{}}
```

**Comment by lamhoangtung** [comment]
@jkhenning. Strangely, I'm also spawning up a new AWS EC2 Instance to create a brand new TRAINS-Server using the official AMI: https://aws.amazon.com/marketplace/pp/B085D8W5NM#pdp-usage

And having the same error with `auth.create_user` call

```json
{"meta":{"id":"1c12135e94e2436690ce30ed01d4cc50","trx":"1c12135e94e2436690ce30ed01d4cc50","endpoint":{"name":"auth.create_user","requested_version":"2.8","actual_version":"1.0"},"result_code":401,"result_subcode":22,"result_msg":"Unauthorized (invalid credentials) (failed to locate provided credentials)","error_stack":null},"data":{}}
```

**Comment by lamhoangtung** [comment]
@jkhenning I just found out that by using "Incognito" mode of my chrome. I was able to see the Username and Password field and be able to login.

Everything else is working great and looks like your `mongo` magic works! Thanks a lot for your help

BTW, I still have two question left:
1. Why I don't see the Password field and unable to login without "Incognito" mode ?
2. What is the default linux user of the official AWS AMI so that I can SSH into it and manually config stuff ?

**Comment by jkhenning** [comment]
@lamhoangtung that's very strange - what I was just about to write is that I see the apiserver reject the WebApp default credentials (used to sign in when not in fixed users mode), which means you're probably running your setup using a fixed users configuration.

I assume some kind of state was left in the browser's cache which caused the WebApp to think the server was running in plain mode (and not in fixed users mode) and thus only displayed the login without user/password. I would try to clear cookies and delete any session storage/state (both are in the Developer section's Application tab)

By the way, can you still attach the complete response to the **auth.fixed_users_mode** request when trying to use non-incognito mode?

To answer your second question, the default user is `ec2-user` :)

**Comment by lamhoangtung** [comment]
@jkhenning Thanks for the answer.

I have tried to get the `auth.fixed_users_mode` response but Chrome debugger say that it "Failed to load response data" ... Are there anything I can do to help ? I will try to postpone any clearing step to help you fix the root of the problem :P

**Comment by jkhenning** [comment]
Happy to help 😄 

Are you sure it's the correct call? There are usually two of them - one is an OPTIONS request, and the other (the one we want) is a GET request...

**Comment by lamhoangtung** [comment]
Hmm, both of the request is "Failed to load response data". Also I can't seem to see if one is a GET or POST request since Chrome only say this:
![Screen Shot 2020-07-28 at 10 58 45 PM](https://user-images.githubusercontent.com/26834698/88690520-f3a6a000-d125-11ea-830d-c6333c27dbdd.png)

**Comment by jkhenning** [comment]
Well, it seems we're limited in debugging this :(

I suggest you try the following:

- Refresh the WebApp using `Ctrl+F5` and see if that helps
- Clear cookies and see if that helps
- Clear session storage/state and see if that helps

**Comment by lamhoangtung** [comment]
1. Reload WebApp doesn't help
2. Clear cookies doesn't help
3. Clear everything including browsing history doesn't help 

T.T Opps. @jkhenning

**Comment by jkhenning** [comment]
... Does it work if you use another browser, like FireFox?

**Comment by lamhoangtung** [comment]
I have try Safari and it's not work as well

**Comment by jkhenning** [comment]
@lamhoangtung this is so strange... It seems either the first requests to the server are always blocked (some network issue or firewall intercepting these calls when not in incognito mode, which is odd), or there is some browser plugin that's affecting these calls and is disabled when using incognito mode?

**Comment by lamhoangtung** [comment]
Thankfully after a few restart of my machine. Everything is working as expected. Thanks a lot for your help @jkhenning <3
